### ISSUE TITLE
How to get a `golangci-lint` with plugin support

### ISSUE THREAD

**Issue by Necropaw** [dbraley/example-linter#2]
`golangci-lint` does not support the call `make vendor_free_build` anymore.

How is it possible to create a plugin with a vendor folder?

**Comment by dbraley** [comment]
Sorry for the late reply, I was unaware that had been removed. I'll try to take a look this weekend and get back to you next week!

**Comment by Necropaw** [comment]
I guess it is not possible. :(

Please remove the reference from https://golangci-lint.run/contributing/new-linters/ to this as this is highly misleading.

**Comment by dbraley** [comment]
Wow, I'm so sorry @Necropaw, I thought I had gotten back to you, but can clearly see I did not. My complete apologies!

I do still need to update the documentation here, I'll do that today. 

Anyway, if I understand your initial problem, it's just that you're unable to use custom linters because you're unable to compile a compatible `golangci-lint` binary? 

Good news! The functionality still exists, you just no longer need to run `make vendor_free_build` in `golangci-lint` as [vendoring was completely removed](https://github.com/golangci/golangci-lint/commit/ef317c460d12c0b89aa96e15486c8b9f99fd4ebc). Now you can just run `make` (or `make build` for a faster test-free build).

You do however still need to make sure linters have matching dependency versions in their go.mod file as the `golangci-lint` project you're using, so it's probably still best to use a locally compiled `golangci-lint` binary (as opposed to `brew install` etc).

Anyway, give it a go and let me know if you have any problems! Good luck!

And again apologies for not getting back to you, I have small child - lack of sleep must have gotten the better of my best attempts to keep my todo-list accurate!
